<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="CustomButton.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="CustomDataGridView.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="CustomGroupBox.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="DoubleBufferAndCustomScrollDataGrid.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="IconButton.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="TextBoxWithPlaceHolder.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="UCDoubleUCTextbox.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UCLabelAndDetail.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UCSlideButton.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UCTextbox1.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UsedForFilters\UCComboBoxFilterOriginal.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UsedForFilters\UCLabelFilterOriginal.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UsedForFilters\UCTextBoxFilterOriginal.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Service Include="{94E38DFF-614B-4cbd-B67C-F211BB35CE8B}" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GlobalFunctions\GlobalFunctions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>