#!/bin/sh
#
# Hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#

msg_file=$1
file_content="$(cat $msg_file)"

# Initialize constants here
export valid_message_regex='^(FEATURE|FIX|TECHNICAL) (#[0-9]+) .+' #ex: Fix #0 VerbInPresent-details...
export error_message="Commit message must match regex \"${valid_message_regex}\""

# Checks if message is valid
if [[ ! $file_content =~ $valid_message_regex ]]; then
 echo "Bad commit \"$file_content\""
 echo $error_message
 exit 1
fi

exit 0