# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more: https://aka.ms/yaml
 
trigger:
    - pipe
 
pool:
  vmImage: windows-latest
 
variables:
  - group: "velopack publish"
 
steps:
  - checkout: self
    path: s
    fetchDepth: 1  # Shallow fetch only the last commit
    clean: true
 

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
    displayName: 'Install .NET'
  
  - task: DotNetCoreCLI@2
    inputs:
     command: 'restore'
     projects: 'MKproject/MKproject.csproj'
 
  - script: dotnet clean
    displayName: 'Clean Solution'
 
  - script: dotnet build --configuration Release
    displayName: 'Build Solution'


  - script: |
      dotnet publish MKproject/MKproject.csproj -c Release -o MKproject/bin/Publish/win-x64 -r win-x64 --self-contained true
    displayName: 'Publish Application'
 
 
  - script: |
      dotnet tool install --global vpk
      vpk download s3  --bucket fox-global --channel win-x64 --endpoint $(minio-upload-url) --keyId $(minio-keyId) --secret $(minio-secret) 
      vpk pack -u MKproject  -v 1.0.23 -p MKproject/bin/Publish/win-x64 -e MKproject.exe --channel win-x64 --packTitle "Fox" --icon MKproject/images/foxlogo.ico --splashImage MKproject/images/foxlogo.ico  --verbose
      vpk upload s3 --bucket fox-global --channel win-x64 --endpoint $(minio-upload-url) --keyId $(minio-keyId) --secret $(minio-secret) 
    displayName: 'Create and Upload Velopack Release'
    env:
      PATH: $(PATH):$(USERPROFILE)\.dotnet\tools
 