# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet
  displayName: 'Install .NET SDK'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'
  displayName: 'Restore NuGet Packages'

- script: |
    dotnet tool install -g GitVersion.Tool
    gitversion /output buildserver
  displayName: 'Install GitVersion'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $GitVersion = gitversion /showvariable FullSemVer
      Write-Output "##vso[build.updatebuildnumber]$GitVersion"
      echo "##vso[task.setvariable variable=GitVersion.FullSemVer]$GitVersion"
      $AssemblyVersion = gitversion /showvariable AssemblySemVer
      echo "##vso[task.setvariable variable=GitVersion.AssemblySemVer]$AssemblyVersion"
      $FileVersion = gitversion /showvariable AssemblySemFileVer
      echo "##vso[task.setvariable variable=GitVersion.AssemblySemFileVer]$FileVersion"
      $InformationalVersion = gitversion /showvariable InformationalVersion
      echo "##vso[task.setvariable variable=GitVersion.InformationalVersion]$InformationalVersion"
  displayName: 'Run GitVersion and Set Variables'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:Version=$(GitVersion.FullSemVer) /p:AssemblyVersion=$(GitVersion.AssemblySemVer) /p:FileVersion=$(GitVersion.AssemblySemFileVer) /p:InformationalVersion=$(GitVersion.InformationalVersion)'
  displayName: 'Build Project'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  displayName: 'Run Tests'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publish Build Artifacts'