# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- pipe

pool:
  vmImage: windows-latest

steps:
- checkout: self
  path: s
  fetchDepth: 1  # Shallow fetch only the last commit
  clean: true


- powershell: |
    $version = 1.0.17
    echo "##vso[task.setvariable variable=version]$version"
  displayName: 'Get Version from Project File'



- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
  displayName: 'Install .NET'
 
- script: |
    dotnet publish MKproject/MKproject.csproj -c Release -o $(Build.ArtifactStagingDirectory)/publish/win-x64 -r win-x64 --self-contained true
  displayName: 'Publish Application'
 
- script: |
    move /y "$(Build.ArtifactStagingDirectory)/publish/win-x64/MKproject.dll" "$(Build.ArtifactStagingDirectory)/publish/win-x64/MKproject.dll"
    copy /y "MKproject/Obfuscator_Output/MKproject.dll" "$(Build.ArtifactStagingDirectory)/publish/win-x64/MKproject.dll"
  displayName: 'Replace DLL with Obfuscated Version'
 
- script: |
    dotnet tool install --global vpk
    vpk download s3  --bucket fox-global --channel win-x64 --endpoint http://198.7.119.42:9000 --keyId M7vOlSs7PznsJwiuGVyE --secret RwPBh65YQ3vi7mFNleszDzLCDe2aP3LSO4RS2Vdm
    vpk pack -u MKproject --channel win-x64 -v $(version) -p $(Build.ArtifactStagingDirectory)/publish/win-x64 
    vpk upload s3 --bucket fox-global --channel win-x64 --endpoint  http://198.7.119.42:9000 --keyId M7vOlSs7PznsJwiuGVyE --secret RwPBh65YQ3vi7mFNleszDzLCDe2aP3LSO4RS2Vdm --publish --releaseName "MKproject $(version)" --tag v$(version)
  displayName: 'Create and Upload Velopack Release'
  env:
    PATH: $(PATH);$(USERPROFILE)\.dotnet\tools
