<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>C:\Users\USER\Downloads\ELKAPP\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <UpdateUrl>http://localhost/MKproject/</UpdateUrl>
    <ApplicationRevision>20</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <PublishWizardCompleted>true</PublishWizardCompleted>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestCertificateThumbprint>2E7FA559FF954D002AFBFE582250A1BBBC23026F</ManifestCertificateThumbprint>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestKeyFile>MKproject_TemporaryKey.pfx</ManifestKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateManifests>true</GenerateManifests>
  </PropertyGroup>
  <PropertyGroup>
    <SignManifests>true</SignManifests>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="Management\buyBundlesOrProductsComponents\UCBundlesOutput.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Management\buyBundlesOrProductsComponents\UCProductOutput.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Management\CalenderComponents\UCCalanderMonth.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Management\NewRegister\UserControls\UCNumberComboButt.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Management\CalenderComponents\LabelMonth.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Management\NewRegister\UserControls\LabelWithIndex.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Management\CalenderComponents\LabelYear.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Management\Statistics\UCComboFilterStat.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Management\BackOffice\UCComboBoxFilterBackOffice.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Management\buyBundlesOrProductsComponents\UCItem.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Management\NewRegister\UserControls\TLPCheckboxesAndRadioOptions.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Management\NewRegister\UserControls\TLPOtherOptions.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Management\SearchClient\UCLabelFilterSearch.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Management\Statistics\UCLabelFilterStatistics.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Management\ClientProfile\UCBundlePackage.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Management\CalenderComponents\UCCalanderYear.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Management\SearchClient\UCComboBoxFilterSearch.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Management\Payment\UCPayments.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Management\NewRegister\UserControls\UCNumberButt.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Management\NewRegister\UserControls\UCNumberLabelButt.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Management\NewRegister\UserControls\UCCamera.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Management\NewRegister\UserControls\UCDoubleCombo.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Schedule\Appointmentform\UCClientApp.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Schedule\CustomisedComboBox\LabelTime.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Schedule\Calanderform\LabelMonth.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Schedule\Calanderform\LabelYearcs.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Schedule\Calanderform\UCCalanderday.cs" />
    <Compile Update="Schedule\Calanderform\UCCalandermonth.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Schedule\Calanderform\UCCalanderyear.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Schedule\Calanderform\UCDays.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Schedule\Tools\TableLayoutPanelBuffered.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Schedule\Tools\TableLayoutPanelDoubleBufferedNoscroll.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Schedule\Availabilityform\UCEmployee.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Schedule\UCData\UCreminder.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Content Include="images\BackOfficeBig.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\BackOfficeSmall.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\Check.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\dollarBig.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\dollarSmall.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\editgray.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\editgreen.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\Editing_pen.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\EmptyIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\Error.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\info.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\maximizee.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\Question.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\restore-down.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\search2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\user.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\user1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\userNude%28smallPixel%29.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\userNude.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\userNudeSmall%28smallPixel%29.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\userNudeSmall.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\view.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\Warning.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\YesOrNo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="nlog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Update="images\checkCircle.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="images\circle.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="images\down-arrow-Black.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="images\down-arrow-BoldColor.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="images\down-arrow-GreenColor.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="images\down-arrow-LighterGreenColor.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="images\eraser.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="images\oval-Small.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="images\xCircle.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="NLog.xsd">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.7.2">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.7.2 %28x86 and x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CustomizedTools\CustomizedTools.csproj" />
    <ProjectReference Include="..\GlobalFunctions\GlobalFunctions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="HIC.System.Windows.Forms.DataVisualization" Version="1.0.1" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.ComponentModel.Composition" Version="8.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="System.Data.SQLite" Version="1.0.118" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Home\Home.cs" />
    <Compile Remove="Home\Home.designer.cs" />
    <EmbeddedResource Remove="Home\Home.resx" />
  </ItemGroup>
</Project>