trigger:
  - master

pool:
  vmImage: ubuntu-latest

jobs:
- job: MergemasterIntoBranches
  displayName: 'Merge master into Custom Branches'
  steps:
  - checkout: self
    persistCredentials: true

  - script: |
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"
      git checkout master
      git pull origin master
      # Merging master into global
      git checkout -b global origin/global
      git merge master --no-ff -m "Merging changes from master into global"
      git push origin global
      # Merging master into elk
      git checkout -b elk origin/elk
      git merge master --no-ff -m "Merging changes from master into elk"
      git push origin elk
      # Merging master into soft
      git checkout -b soft origin/soft
      git merge master --no-ff -m "Merging changes from master into soft"
      git push origin soft
    displayName: 'Fetch master and Merge into Branches'
