trigger:
  - master

pool:
  vmImage: ubuntu-latest

jobs:
- job: MergemasterIntoBranches
  displayName: 'Merge master into Custom Branches'
  steps:
  - checkout: self
    persistCredentials: true

  - script: |
      git checkout master
      git pull origin master
    
      function merge_branch {
        local branch=$1
        git fetch -a     
        git checkout $branch      
        git merge master --no-ff -m "Merging changes from master into $branch"
      }
      merge_branch "global"
      merge_branch "elk"
      merge_branch "soft"
    displayName: 'Fetch master and Merge into Branches'
